version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  build:
    docker:
      - image: cimg/node:14.15.0
      - image: circleci/mongo:4.4.1-ram
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npm run seed
      - run: npm test